# Generated by Django 3.1.1 on 2020-09-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='images/articles/%Y/%m/%d'),
        ),
    ]
