# Generated by Django 3.1.1 on 2020-09-17 06:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='article/'),
        ),
    ]
