# Generated by Django 3.1.1 on 2020-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_article_article_additional_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(help_text='Статья'),
        ),
    ]
