# Generated by Django 3.1.1 on 2020-09-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200917_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_additional_title',
            field=models.CharField(blank=True, help_text='Подназвание', max_length=400),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='article/'),
        ),
    ]
