# Generated by Django 3.1.1 on 2020-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200917_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_additional_title',
            field=models.CharField(blank=True, max_length=400, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='article/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, verbose_name='Название статьи'),
        ),
    ]
