# Generated by Django 3.1.1 on 2020-09-19 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0011_auto_20200919_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(2, 'Модератор'), (1, 'Администратор'), (3, 'Гость')]),
        ),
    ]
