# Generated by Django 3.1.1 on 2020-09-22 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0015_auto_20200922_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(3, 'Гость'), (2, 'Модератор'), (1, 'Администратор')]),
        ),
    ]
