# Generated by Django 3.1.1 on 2020-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200922_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(3, 'Гость'), (1, 'Администратор'), (2, 'Модератор')]),
        ),
    ]
