# Generated by Django 3.1.1 on 2020-09-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200922_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(2, 'Модератор'), (3, 'Гость'), (1, 'Администратор')]),
        ),
    ]
