# Generated by Django 3.1.1 on 2020-09-23 05:56

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20200923_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='article_title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(3, 'Гость'), (2, 'Модератор'), (1, 'Администратор')]),
        ),
    ]
